# RSS_FEEDS = [
#     'https://www.gazeta.ru/export/rss/first.xml',
#     'https://www.interfax.ru/rss',
#     'https://nplus1.ru/rss',
#     'https://www.sports.ru/export/rss2/posts.xml',
#     "https://lenta.ru/rss/news",
#     "https://lenta.ru/rss/articles",
#     "https://ria.ru/export/rss2/index.xml",
#     "https://www.tass.ru/rss/v2.xml",
#     "https://www.kommersant.ru/RSS/news.xml",
#     "https://pravda.ru/export.xml",
#     "https://lenta.ru/rss/news/russia",
#     "https://lenta.ru/rss/news/world",
#     "https://lenta.ru/rss/news/economics",
#     "https://lenta.ru/rss/top7",
#     "https://lenta.ru/rss/last24",
#     "https://lenta.ru/rss/articles",
#     "https://lenta.ru/rss/columns",
#     "https://rg.ru/xml/index.xml",
#     "https://www.mk.ru/rss/index.xml",
#     'https://ria.ru/export/rss2/archive/',
#     'https://ria.ru/export/rss2/archive/index.xml',
#     'https://www.interfax.ru/rss',
#     'https://www.kommersant.ru/RSS/main.xml',
#     'https://www.vedomosti.ru/rss/news',
#     'https://iz.ru/xml/rss/all.xml',
#     'https://3dnews.ru/news/rss/',
#     'https://www.ferra.ru/export/rss',
#     'https://www.ixbt.com/export/news.xml',
#     'https://nauka.tass.ru/rss/v2.xml',
#     'https://elementy.ru/rss',
#     'https://www.championat.com/news/feed.xml',
#     'https://www.sovsport.ru/rss',
#     'https://www.mk.ru/rss/culture/index.xml',
#     'https://news.rambler.ru/rss',
#     'https://news.mail.ru/rss',
#     'https://yandex.ru/news/rss',
#     "https://www.kommersant.ru/RSS/news.xml",
#     "https://rg.ru/xml/index.xml",
#     "https://www.mk.ru/rss/economics/",
#     "https://www.mk.ru/rss/politics/",
#     "https://province.ru/rss",
#     "https://rss.rnsinfo.ru/",
#     "https://nnews.nnov.ru/rss",
#     "https://vm.ru/rss",
#     "https://chita.ru/rss-feeds/rss.xml",
#     "https://feeds.feedburner.com/amic/news",
#     "https://eg-online.ru/news/news_rss.php",
#     "https://nvo.ng.ru/rss",
#     "https://pravdasevera.ru/rss",
#     "https://fine-news.ru/feed",
#     "https://meduza.io/rss2/all",
#     "https://adigea.aif.ru/rss/googlearticles.xml",
#     "https://m24.ru/rss",
# ]

RSS_FEEDS = [
    "https://ria.ru/export/rss2/index.xml",
    "https://tass.ru/rss/v2.xml",
    "https://www.interfax.ru/rss",
    "https://www.kommersant.ru/RSS/news.xml",
    "https://www.vedomosti.ru/rss/news",
    "https://nplus1.ru/rss",
    "https://3dnews.ru/news/rss/",
    "https://www.sports.ru/export/rss2/posts.xml",
    "https://meduza.io/rss2/all",
    "https://lenta.ru/rss/news",
]